[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
build_info = true
ast = true
extra_output = ["storageLayout"]
solc_version = "0.8.25"
evm_version = "cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin4/contracts=lib/v3-periphery/lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
    "@tokenbound/contracts=lib/tokenbound/src",
    "@tokenbound/erc6551=lib/tokenbound/lib/erc6551/src",
    "@uniswap/swap-router-contracts=lib/swap-router-contracts/",
    "@uniswap/v3-core=lib/v3-core/",
    "@uniswap/v3-periphery=lib/v3-periphery/"
    ]

[fuzz]
runs = 100
seed = "0x2"

[invariant]
runs = 100
depth = 5
fail_on_revert = false

[rpc_endpoints]
anvil="${ANVIL_RPC_URL}"
base_mainnet="${BASE_MAINNET_RPC}"
base_sepolia="${BASE_SEPOLIA_RPC}"

